name:  ci python

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  on_build_actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-python@v1
        with: 
          python-version: 3.6
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: test with unitest
        run:  python -m unittest discover tests/ 


